// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnlyIT9kyb72Tp29RRTlEnT1w13JD9v3E',
    appId: '1:1078032220525:web:c55861d25f25ff5ea25a64',
    messagingSenderId: '1078032220525',
    projectId: 'imagesuta',
    authDomain: 'imagesuta.firebaseapp.com',
    storageBucket: 'imagesuta.firebasestorage.app',
    measurementId: 'G-L9Z2XM120D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCprlU1dRw8IjSPDjgmAf1VsfpkUCZYYKI',
    appId: '1:1078032220525:android:95d413d2e2f40ec3a25a64',
    messagingSenderId: '1078032220525',
    projectId: 'imagesuta',
    storageBucket: 'imagesuta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnv7_UbD3cdJtpZjLRVEyjfvSKOqlGg-Q',
    appId: '1:1078032220525:ios:80e2a53565fc7dc0a25a64',
    messagingSenderId: '1078032220525',
    projectId: 'imagesuta',
    storageBucket: 'imagesuta.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnv7_UbD3cdJtpZjLRVEyjfvSKOqlGg-Q',
    appId: '1:1078032220525:ios:80e2a53565fc7dc0a25a64',
    messagingSenderId: '1078032220525',
    projectId: 'imagesuta',
    storageBucket: 'imagesuta.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnlyIT9kyb72Tp29RRTlEnT1w13JD9v3E',
    appId: '1:1078032220525:web:1f6f1022c99d6fada25a64',
    messagingSenderId: '1078032220525',
    projectId: 'imagesuta',
    authDomain: 'imagesuta.firebaseapp.com',
    storageBucket: 'imagesuta.firebasestorage.app',
    measurementId: 'G-K50M5KZDDM',
  );
}
